name: 'Monorepo random controller'
description: 'Detect applications that have changes and not'
inputs:
  dir:
    description: "Applications dir"
    required: true
outputs:
  apps:
    description: "Applications list"
    value: ${{ toJson(fromJson(steps.controller.outputs.apps)) }}

  changes:
    description: "Applications that have changes"
    value: ${{ toJson(fromJson(steps.controller.outputs.changes)) }}
  no-changes:
    description: "Applications that have no changes"
    value: ${{ toJson(fromJson(steps.controller.outputs.no-changes)) }}
runs:
  using: "composite"
  steps:
    - name: 'Install jq 1.6'
      uses: dcarbone/install-jq-action@v1.0.1
      with:
        version: 1.6
        force: 'true'

    - name: Analize code
      id: controller
      shell: bash
      run: |
        CHANGES=()
        NO_CHANGES=()
        
        APPS=($(ls ${{ inputs.dir }}))
        for i in "${APPS[@]}"
        do
            NUMBER=$(( $RANDOM % 100 ))
            if [[ $NUMBER -ge 50 ]]; then
                CHANGES+=(${i})
            else
                NO_CHANGES+=(${i})
            fi
        done

        APPS_RESULT="$(echo ${APPS[@]} | jq --compact-output --raw-input 'split(" ")')"
        CHANGES_RESULT="$(echo ${CHANGES[@]} | jq --compact-output --raw-input 'split(" ")')"
        NO_CHANGES_RESULT="$(echo ${NO_CHANGES[@]} | jq --compact-output --raw-input 'split(" ")')"
        
        echo "changes=${APPS_RESULT//\"/\\\"}"        
        echo "changes=${CHANGES_RESULT//\"/\\\"}"
        echo "no-changes=${NO_CHANGES_RESULT//\"/\\\"}"
        
        echo "apps=${APPS_RESULT}" >> $GITHUB_OUTPUT        
        echo "changes=${CHANGES_RESULT}" >> $GITHUB_OUTPUT
        echo "no-changes=${NO_CHANGES_RESULT}" >> $GITHUB_OUTPUT
